In [23]:
import numpy as np
import json
from scipy.sparse import load_npz
import os

In [24]:
cwd = os.getcwd()

print(cwd)

/Users/sivaguganjayachandran/PycharmProjects/data-mining-graph-theory-project


In [25]:
# Load adjacency matrix (sparse)
adj = load_npz('data/adj.npz')

# Load node features
features = np.load('data/features.npy')

# Load labels
labels = np.load('data/labels.npy')

# Load train/test splits
with open('data/splits.json', 'r') as f:
    splits = json.load(f)

# Access splits like this:
idx_train = splits['idx_train']
idx_test = splits['idx_test']

In [27]:
labels

array([2, 1, 3, 2, 6, 5, 2, 2, 6, 2, 2, 2, 2, 1, 6, 1, 2, 6, 2, 6, 2, 4,
       2, 5, 6, 4, 4, 2, 4, 6, 3, 2, 3, 1, 4, 2, 1, 4, 3, 0, 1, 6, 2, 3,
       3, 3, 2, 1, 6, 0, 3, 0, 2, 2, 2, 1, 2, 2, 1, 3, 2, 4, 6, 0, 1, 0,
       4, 2, 2, 2, 1, 2, 6, 0, 6, 3, 3, 6, 0, 3, 1, 1, 6, 5, 6, 0, 4, 3,
       1, 3, 2, 2, 2, 1, 6, 3, 2, 1, 2, 2, 6, 2, 1, 5, 3, 4, 2, 3, 1, 0,
       3, 6, 6, 2, 2, 1, 2, 1, 2, 1, 3, 2, 2, 3, 0, 2, 4, 5, 5, 1, 2, 0,
       6, 2, 2, 2, 4, 6, 2, 3, 2, 4, 2, 0, 2, 2, 6, 0, 2, 2, 1, 0, 4, 5,
       3, 1, 3, 6, 4, 0, 0, 1, 3, 1, 6, 2, 2, 5, 2, 1, 5, 0, 2, 6, 6, 4,
       6, 2, 4, 6, 6, 6, 3, 6, 4, 6, 2, 3, 0, 6, 5, 2, 0, 0, 4, 2, 2, 0,
       6, 6, 1, 6, 1, 6, 1, 3, 6, 1, 2, 5, 2, 2, 2, 3, 6, 6, 4, 3, 2, 4,
       3, 0, 1, 1, 2, 1, 6, 2, 4, 3, 3, 2, 3, 6, 3, 3, 2, 4, 3, 6, 2, 6,
       3, 1, 2, 0, 2, 1, 2, 2, 0, 2, 3, 1, 5, 3, 6, 3, 3, 3, 3, 2, 2, 1,
       5, 2, 3, 2, 6, 6, 6, 1, 5, 4, 1, 6, 1, 5, 2, 2, 4, 3, 2, 3, 2, 1,
       3, 0, 1, 1, 3, 1, 3, 0, 0, 2, 4, 1, 6, 0, 2,

In [28]:
labels.shape

(496,)

Labels are provided only for the traning data. We have to predict the test dataset.

Train/Test : 496/1984

Total : 2480

In [29]:
features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
features.shape

(2480, 1390)

In [31]:
idx_train

[2252,
 1965,
 578,
 107,
 244,
 414,
 186,
 702,
 409,
 2406,
 1212,
 2360,
 2440,
 799,
 1335,
 417,
 2231,
 753,
 2403,
 1265,
 1334,
 513,
 1258,
 617,
 881,
 2005,
 334,
 317,
 1152,
 852,
 1707,
 783,
 1431,
 990,
 952,
 1479,
 524,
 1398,
 1565,
 1279,
 529,
 1587,
 1615,
 1845,
 452,
 1848,
 1712,
 1043,
 180,
 1278,
 1508,
 34,
 611,
 77,
 453,
 1536,
 231,
 1135,
 1083,
 1107,
 2168,
 984,
 1736,
 533,
 2431,
 1456,
 1297,
 614,
 2161,
 426,
 1901,
 1341,
 351,
 2412,
 343,
 2232,
 2250,
 2418,
 326,
 1128,
 1287,
 959,
 658,
 1730,
 1759,
 1971,
 2451,
 2110,
 330,
 2210,
 1369,
 208,
 1920,
 814,
 2374,
 2115,
 1171,
 3,
 2229,
 656,
 975,
 203,
 964,
 1925,
 572,
 2275,
 967,
 437,
 1944,
 79,
 1483,
 1005,
 1501,
 2257,
 1529,
 1878,
 1416,
 2121,
 152,
 1872,
 2078,
 2351,
 830,
 2353,
 1162,
 2419,
 1188,
 9,
 488,
 1534,
 1679,
 1236,
 639,
 316,
 490,
 2172,
 934,
 2286,
 1758,
 122,
 2295,
 448,
 2220,
 1045,
 1711,
 1549,
 532,
 1985,
 2253,
 259,
 1931,
 1467,
 109

In [32]:
adj

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 10100 stored elements and shape (2480, 2480)>

In [33]:
adj_dense = adj.toarray()

In [34]:
adj_dense

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [35]:
adj_dense.shape

(2480, 2480)

In [36]:
adj_dense.sum(axis=0)

array([5., 4., 1., ..., 3., 4., 1.], dtype=float32)